# Copyright and License Information -------------------------------------------
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Contacts and bug reports ----------------------------------------------------
# 
# Chao Xiao
# xiaochao369@hust.edu.cn


# Description -----------------------------------------------------------------
# 
# The MLR_model_13_CpG model is a multiple linear regression (MLR) model, 
# including 14 age-related CpG (AR-CpG) sites, namely chr2:129071885 (cg19998819), 
# chr10:4384066 (cg12277678), chr13:32846238 (cg18037145), chr21:45509586 (cg04123357),
# chr16:65834073 (cg25187042), chr17:29574049 (cg13872326), chr13:93039685, 
# chr12:123465627 (cg21843517), chr12:4535197 (cg11262154), chr13:93039687, 
# chr1:19339503, chr11:89589683 (cg06979108), and chr8:54102463 (cg03030301-20). 
# This model can be used to estimate individual age from semen or sperm DNA.
# 
# Input: a table in either a '.txt' (tab-separated file) or in a '.csv'
# (comma-separated) format. Ensure that the data is organized as specified below
# and includes at least the following columns: "Sample.Name", "Marker", and
# "Meth_level". The "Meth_level" represents DNA methylation levels generated by 
# massively parallel sequencing technologies, such as bisulfite amplicon sequencing. 
# The values should be expressed as percentages and fall within the range of 0 to 100.
# 
# An example in '.txt' (tab-separated file) format:
# 
# Sample.Name	Marker	Meth_level  ...
# SN001	chr2.129071885	60.18492  ...
# SN001	chr10.4384066	45.66817  ...
# SN001	chr13.32846238	48.32148  ...
# SN001	chr21.45509586	68.60531  ...
# SN001	chr16.65834073	49.76106  ...
# SN001	chr17.29574049	78.81048  ...
# SN001	chr13.93039685	54.75997  ...
# SN001	chr12.123465627	51.33506  ...
# SN001	chr12.4535197	73.74337  ...
# SN001	chr13.93039687	52.21047  ...
# SN001	chr1.19339503	59.85325  ...
# SN001	chr11.89589683	62.36365  ...
# SN001	chr8.54102463	47.87679  ...
#
# An example in '.csv' (comma-separated) format:
# 
# Sample.Name,Marker,Meth_level,...
# SN001,chr2.129071885,60.18492,...
# SN001,chr10.4384066,45.66817,...
# SN001,chr13.32846238,48.32148,...
# SN001,chr21.45509586,68.60531,...
# SN001,chr16.65834073,49.76106,...
# SN001,chr17.29574049,78.81048,...
# SN001,chr13.93039685,54.75997,...
# SN001,chr12.123465627,51.33506,...
# SN001,chr12.4535197,73.74337,...
# SN001,chr13.93039687,52.21047,...
# SN001,chr1.19339503,59.85325,...
# SN001,chr11.89589683,62.36365,...
# SN001,chr8.54102463,47.87679,...
# 
# Output: the donor's age estimated by the MLR_model_13_CpG model.


# Encode statement ------------------------------------------------------------
# -*- coding: UTF-8 -*-


## Load packages --------------------------------------------------------------
if (!requireNamespace("caret", quietly = TRUE))
  install.packages("caret", dependencies = c("Depends", "Suggests"))
library(caret)  # for model calling
if (!requireNamespace("dplyr", quietly = TRUE))                     
  install.packages("dplyr")
library(dplyr)  # for data wrangling
if (!requireNamespace("tidyr", quietly = TRUE))                     
  install.packages("tidyr")
library(tidyr)  # for data wrangling
if (!requireNamespace("data.table", quietly = TRUE))                     
  install.packages("data.table")
library(data.table)  # for data wrangling

## Load model ---------------------------------------------------------
# https://github.com/XiaoChao369/Li-et-al-2024-age-semen-models
setwd(dirModel)
MLR_model_13_CpG <- readRDS("MLR_model_13_CpG.RDS")

## Prepare data ---------------------------------------------------------------
# Read the methylation data
setwd(dirData)
meth_data <- data.table::fread("SN001_MLR_model_13_CpG.txt", header = TRUE)

#     Sample.Name          Marker Meth_level
#          <char>          <char>      <num>
#   1:       SN001  chr2.129071885   60.18492
# 2:       SN001   chr10.4384066   45.66817
# 3:       SN001  chr13.32846238   48.32148
# 4:       SN001  chr21.45509586   68.60531
# 5:       SN001  chr16.65834073   49.76106
# 6:       SN001  chr17.29574049   78.81048
# 7:       SN001  chr13.93039685   54.75997
# 8:       SN001 chr12.123465627   51.33506
# 9:       SN001   chr12.4535197   73.74337
# 10:       SN001  chr13.93039687   52.21047
# 11:       SN001   chr1.19339503   59.85325
# 12:       SN001  chr11.89589683   62.36365
# 13:       SN001   chr8.54102463   47.87679

# Subset data
markers <- c("chr2.129071885", "chr10.4384066", "chr13.32846238", 
             "chr21.45509586", "chr16.65834073", "chr17.29574049",
             "chr13.93039685", "chr12.123465627", "chr12.4535197", 
             "chr13.93039687", "chr1.19339503", "chr11.89589683",
              "chr8.54102463")
meth_data <- meth_data %>%
  dplyr::filter(Marker %in% markers)

# Check data
stopifnot(exprs = {
  isTRUE(sum(unique(meth_data$Marker) %in% markers) != 0)
  isTRUE(sum(markers %in% unique(meth_data$Marker)) != 0)
  isTRUE((nrow(meth_data) %% length(markers)) %in% 0)
})

# Save methylation data into a .csv file
setwd(dirResult)
write.csv(meth_data, "meth_data_MLR_model_13_CpG.csv", quote = FALSE, row.names = FALSE)

# Convert long data to wide data
meth_data <- ungroup(meth_data) %>%
  tidyr::spread(key = Marker, value = Meth_level)

#  Sample.Name chr1.19339503 chr10.4384066 chr11.89589683 chr12.123465627 chr12.4535197
#        SN001      59.85325      45.66817       62.36365        51.33506      73.74337
#  chr13.32846238 chr13.93039685 chr13.93039687 chr16.65834073 chr17.29574049 chr2.129071885 chr21.45509586
#        48.32148       54.75997       52.21047       49.76106       78.81048       60.18492       68.60531
#  chr8.54102463
#       47.87679

## Estimate age using the MLR_model_13_CpG model ---------------------------------------
# Estimate age
estimated_age <- data.frame(
  Sample.Name = meth_data$Sample.Name,
  Estimated.Age = predict(MLR_model_13_CpG, newdata = meth_data[,-1])
)
# Save estimated ages into a .csv file
setwd(dirResult)
write.csv(estimated_age, "estimated_age_MLR_model_13_CpG.csv", quote = FALSE, 
          row.names = FALSE)
# Print estimated ages to the R console
print(estimated_age)

#  Sample.Name Estimated.Age
#        SN001      25.27936


