# Copyright and License Information -------------------------------------------
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Contacts and bug reports ----------------------------------------------------
# 
# Chao Xiao
# xiaochao369@hust.edu.cn


# Description -----------------------------------------------------------------
# 
# The RF_model_9_CpG_drrbs model is a random forest (RF) model, including 9 age-related 
# CpG (AR-CpG) sites identified by dRRBS, namely chr13:93039685, chr1:19339492, 
# chrUn_GL000220v1:118890, chr1:19339500, chr1:19339447, chr13:93039687, 
# chr16:54736316, chrUn_GL000220v1:118888, and chr1:19339432. This model can be 
# used to estimate individual age from semen or sperm DNA.
# 
# Input: a table in either a '.txt' (tab-separated file) or in a '.csv'
# (comma-separated) format. Ensure that the data is organized as specified below
# and includes at least the following columns: "Sample.Name", "Marker", and
# "Meth_level". The "Meth_level" represents DNA methylation levels generated by 
# massively parallel sequencing technologies, such as bisulfite amplicon sequencing. 
# The values should be expressed as percentages and fall within the range of 0 to 100.
# 
# An example in '.txt' (tab-separated file) format:
# 
# Sample.Name	Marker	Meth_level  ...
# SN001	chrUn_GL000220v1.118890	14.973  ...
# SN001	chr13.93039685	54.75997  ...
# SN001	chrUn_GL000220v1.118888	16.01179  ...
# SN001	chr1.19339492	52.7433  ...
# SN001	chr16.54736316	66.3298  ...
# SN001	chr1.19339500	58.30626  ...
# SN001	chr1.19339447	43.62603  ...
# SN001	chr13.93039687	52.21047  ...
# SN001	chr1.19339432	55.06322  ...
# 
# An example in '.csv' (comma-separated) format:
# 
# Sample.Name,Marker,Meth_level,...
# SN001,chrUn_GL000220v1.118890,14.973,...
# SN001,chr13.93039685,54.75997,...
# SN001,chrUn_GL000220v1.118888,16.01179,...
# SN001,chr1.19339492,52.7433,...
# SN001,chr16.54736316,66.3298,...
# SN001,chr1.19339500,58.30626,...
# SN001,chr1.19339447,43.62603,...
# SN001,chr13.93039687,52.21047,...
# SN001,chr1.19339432,55.06322,...
# 
# Output: the donor's age estimated by the RF_model_9_CpG_drrbs model.


# Encode statement ------------------------------------------------------------
# -*- coding: UTF-8 -*-


## Load packages --------------------------------------------------------------
if (!requireNamespace("caret", quietly = TRUE))
  install.packages("caret", dependencies = c("Depends", "Suggests"))
library(caret)  # for model calling
if (!requireNamespace("dplyr", quietly = TRUE))                     
  install.packages("dplyr")
library(dplyr)  # for data wrangling
if (!requireNamespace("tidyr", quietly = TRUE))                     
  install.packages("tidyr")
library(tidyr)  # for data wrangling
if (!requireNamespace("data.table", quietly = TRUE))                     
  install.packages("data.table")
library(data.table)  # for data wrangling

## Load model ---------------------------------------------------------
# https://github.com/XiaoChao369/Li-et-al-2024-age-semen-models
setwd(dirModel)
RF_model_9_CpG_drrbs <- readRDS("RF_model_9_CpG_drrbs.RDS")

## Prepare data ---------------------------------------------------------------
# Read the methylation data
setwd(dirData)
meth_data <- data.table::fread("SN001_RF_model_9_CpG_drrbs.txt", header = TRUE)

#    Sample.Name                  Marker Meth_level
#         <char>                  <char>      <num>
#   1:       SN001 chrUn_GL000220v1.118890   14.97300
# 2:       SN001          chr13.93039685   54.75997
# 3:       SN001 chrUn_GL000220v1.118888   16.01179
# 4:       SN001           chr1.19339492   52.74330
# 5:       SN001          chr16.54736316   66.32980
# 6:       SN001           chr1.19339500   58.30626
# 7:       SN001           chr1.19339447   43.62603
# 8:       SN001          chr13.93039687   52.21047
# 9:       SN001           chr1.19339432   55.06322

# Subset data
markers <- c("chrUn_GL000220v1.118890", "chr13.93039685", 
             "chrUn_GL000220v1.118888", "chr1.19339492",          
             "chr16.54736316", "chr1.19339500", "chr1.19339447", 
             "chr13.93039687", "chr1.19339432")
meth_data <- meth_data %>%
  dplyr::filter(Marker %in% markers)

# Check data
stopifnot(exprs = {
  isTRUE(sum(unique(meth_data$Marker) %in% markers) != 0)
  isTRUE(sum(markers %in% unique(meth_data$Marker)) != 0)
  isTRUE((nrow(meth_data) %% length(markers)) %in% 0)
})

# Save methylation data into a .csv file
setwd(dirResult)
write.csv(meth_data, "meth_data_RF_model_9_CpG_drrbs.csv", quote = FALSE, row.names = FALSE)

# Convert long data to wide data
meth_data <- ungroup(meth_data) %>%
  tidyr::spread(key = Marker, value = Meth_level)

# Sample.Name chr1.19339432 chr1.19339447 chr1.19339492 chr1.19339500 chr13.93039685 chr13.93039687
#       SN001      55.06322      43.62603       52.7433      58.30626       54.75997       52.21047
# chr16.54736316 chrUn_GL000220v1.118888 chrUn_GL000220v1.118890
#        66.3298                16.01179                  14.973

## Estimate age using the RF_model_9_CpG_drrbs model ---------------------------------------
# Estimate age
estimated_age <- data.frame(
  Sample.Name = meth_data$Sample.Name,
  Estimated.Age = predict(RF_model_9_CpG_drrbs, newdata = meth_data[,-1])
)
# Save estimated ages into a .csv file
setwd(dirResult)
write.csv(estimated_age, "estimated_age_RF_model_9_CpG_drrbs.csv", quote = FALSE, 
          row.names = FALSE)
# Print estimated ages to the R console
print(estimated_age)

#   Sample.Name Estimated.Age
#         SN001      29.78108


